import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  overlay: {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: "rgba(0, 0, 0, 0.5)",
  justifyContent: "center", 
  alignItems: "center",
},
  container: {
    flexGrow: 1,
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'white',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
     marginTop: 50,
  },
  headerIcon: {
    borderWidth: 2,
    borderColor: 'black',
    borderRadius: 10,
    width: 25,
    height: 25,
    padding: 4,
    resizeMode: 'contain',
  },
  headerIconRed: {
    borderWidth: 2,
    color: 'white',
    backgroundColor: '#FF4A4A',
    borderRadius: 10,
    width: 20,
    height: 20,
    padding: 4,
    resizeMode: 'contain',
  },
  progressFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FF880A',
  },
  headerTitleContainer: {
    justifyContent: 'center',
    height: 20,
  },
  progressBar: {
    height: 15,
    flexDirection: 'row',
    width: 200,
    backgroundColor: '#CACACA',
    borderColor: '#FFF',
    borderWidth: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  editorContainer: {
    padding: 20,
    borderWidth: 2,
    borderColor: 'black',
    borderRadius: 10,
    backgroundColor: '#d1d5db',
    height: 305,
    width: 360,
    position: 'relative',
  },
  editorBorder: {
    borderWidth: 2,
    justifyContent: 'center',
    borderColor: 'black',
    borderRadius: 10,
    padding: 4,
    height: 238,
  },
  editorInnerBorder: {
    borderWidth: 2,
    justifyContent: 'center',
    borderColor: 'black',
    borderRadius: 10,
    height: 220,
  },
  editorContent: {
    backgroundColor: '#2B2E28',
    padding: 5,
    borderRadius: 10,
    height: 220,
    justifyContent: 'center',
  },
  editorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 6,
    backgroundColor: '#0A8DFF',
  },
  editorHeaderD: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    backgroundColor: '#FCF9F9',
  },
  editorButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    justifyContent: 'flex-end',
  },
  editorButton: {
    width: 20,
    height: 20,
    backgroundColor: '#D9D9D9',
    borderRadius: 5,
  },
  editorHeaderText: {
    color: 'black',
    fontWeight: 'bold',
  },
  editorHeaderTextEnd: {
    color: 'black',
    fontSize: 10,
    gap: 5,
    fontWeight: 'bold',
    alignSelf: 'flex-end',
    textAlign: 'right',
  },
  editorCode: {
    color: '#FFBE0A',
    marginTop: 20,
    fontSize: 16,
    fontWeight: 'bold',
  },
    inputContainer: {
      borderWidth: 2,
      borderColor: 'black',
      borderRadius: 10,
      padding: 10,
      height: 150,
      width: '90%',
      alignSelf: 'center',
    },

    input: {
      flex: 1, // <<< adiciona isso
      fontSize: 16,
      color: '#374151',
    },
  button: {
    backgroundColor: '#FF880A',
    padding: 10,
    borderRadius: 50,
    width: 150,
    textAlign: 'center',
    boxShadow: '0px 2px 3px 0px #9E9E9E',
  },
   button_erro: {
    backgroundColor: '#FF4A4A',
    padding: 10,
    borderRadius: 50,
    width: 150,
    textAlign: 'center',
    boxShadow: '0px 2px 3px 0px #9E9E9E',
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 15,
  },
  buttonText_erro: {
    color: 'white',
    textAlign: 'center',
    fontSize: 15,
  },
  toggleButton: {
    backgroundColor: '#FF880A',
    display: "flex",
    alignItems: "center",
    marginTop: 20,
    padding: 10,
    borderRadius: 50,
    width: 150,
    boxShadow: '0px 2px 3px 0px #9E9E9E',
  },
  disabledButton: {
    backgroundColor: '#CCCCCC',
  },
  toggleButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  card: {
    marginTop: 20,
    padding: 20,
    backgroundColor: '#FFECD8',
    width: 300,
    height:250,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: "center",
    boxShadow: '0px 2px 3px 0px #9E9E9E',
  },
  cardTitle: {
    color: '#FF880A',
    fontWeight: "bold",
    fontSize: 20,
  },
    cardSubText: {
    textAlign: 'center',
    fontWeight: 'bold',
  },
  cardText: {
    textAlign: 'center',
  },
    card_erro: {
    marginTop: 20,
    padding: 20,
    backgroundColor: '#FFE8E8',
    width: "250px",
    height:"200px",
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: "center",
    boxShadow: '0px 2px 3px 0px #9E9E9E',
  },
    card_header: {
    flexDirection: 'row',
    alignItems: 'center',
  },
    cardTitle_erro: {
    color: '#CF0000',
    fontWeight: "bold",
    fontSize: 20,
  },
});

export default styles;
